adj1=input('Type a adjective:')
n1=input('Type a noun:')
vp1=input('Type a past tense verb:')
adv1=input('Type an adverb:')
adj2=input('Type an adjective:')
n2=input('Type a noun:')
n3=input('Type a noun:')
adj3=input('Type an adjective:')
v1=input('Type a verb:')
adv2=input('Type an adverb:')
vp2=input('Typr a past tense verb:')
adj4=input('Type an adjective:')
print("Today I went to the zoo. I saw a "+adj1+" "+n1+" jumping up and down its tree. He "+vp1+" "+adv1+" through the large tunnel that led to its "+adj2+" "+n2+". I got some peanuts and passed them through the cage to a gigantic gray "+n3+" towering above my head. Feeding that animal made me hungry. I went to get a "+adj3+" scoop of ice cream. It filled my stomach. Afterwards I had to "+v1+" "+adv2+" to catch our bus. When I got home I "+vp2+" my mom for a "+adj4+" day at the zoo.")
